title: CubeLab Media
webowner: Thaddius Lord
email: thaddius@cubelabmedia.com
description: Creative writers, video gamers, bloggers, Dungeons & Dragons players, musicians, creators, and fairly nice guys.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cubelabmedia.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Thaddius Lord
twitter_username: thaddiuslord

social:
  name: Thaddius Lord | CubeLab Media
  links:
    - https://twitter.com/cubelabmedia
    - https://www.facebook.com/cubelabmedia

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://cubelabmedia.com'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - CNAME
    - Gamefile
    - Gemfile.lock
    - readme.md
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "feature"
        field:
          element: "text"
          label: "Add Feature Image to Post"
          placeholder: "Image path (relative to /assets/featured-image/)"
          alterable: true
      - name: "comments"
        field:
          element: "text"
          label: "Enable/Disable Comments"
          placeholder: "Select (default Enabled)"
          value: "true"
          options:
            - name: "Enable"
              value: "true"
            - name: "Disable"
              value: "false"
